name: depprior
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - xgboost
  - matplotlib
  - seaborn
  - statsmodels
  - jupyter
  - ipython
  - openpyxl
  - pillow
  - networkx
  - requests
  - scanpy
  - gseapy
  - r-base=4.5
  - r-survival
  - r-dplyr
  - r-readr
  - r-tidyr
  - r-tibble
  - r-ggplot2
  - r-forcats
  - r-purrr
  - r-patchwork
  - r-rcolorbrewer
  - r-biocmanager
  - r-survminer
  - r-circlize
  - bioconductor-tcgabiolinks
  - bioconductor-summarizedexperiment
  - bioconductor-genomicranges
  - bioconductor-complexheatmap
  - bioconductor-maftools
  - bioconductor-ensembldb
  - bioconductor-ensdb.hsapiens.v86
  - bioconductor-illuminahumanmethylation450kanno.ilmn12.hg19
  - pip
  - pip:
      - lifelines
      - omicverse
